# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod Info
archives_base_name = CreateSpawnerBoxer
mod_version = 0.1.2
maven_group = io.github.cvrunmin.createspawnerboxer
mod_id = createspawnerboxer

minecraft_version = 1.21.1
minecraft_version_range = 1.21.1

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version = 2024.11.17

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version = 21.1.219
neoforge_loader_version = 4

# Create - Forge
# https://wiki.createmod.net/developers/depend-on-create/neoforge-1.21.1
create_forge_version = 6.0.10-280
ponder_version = 1.0.82
registrate_forge_version = MC1.21-1.3.0+67
flywheel_forge_minecraft_version = 1.21.1
flywheel_forge_version = 1.0.6

# Development QOL
# Create Fabric supports all 3 recipe viewers: JEI, REI, and EMI. This decides which is enabled at runtime.
# set to disabled to have none of them.
fabric_recipe_viewer = jei
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version = 19.21.0.247